disabled_rules:
    - large_tuple
    - trailing_whitespace
    - colon
    - force_cast
    - nesting
    - orphaned_doc_comment
    - multiple_closures_with_trailing_closure
    - unused_closure_parameter
opt_in_rules:
    - empty_count

excluded:
    - Carthage
    - Pods
    - SwiftLint/Common/3rdPartyLib
# analyzer_rules: # Rules run by `swiftlint analyze`
#   - explicit_self

line_length:
    warning: 200
    error: 250
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
identifier_name:
  excluded: # excluded via string array
    - i
    - j
    - vc
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"

